services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - my-db-volume:/var/lib/mysql
volumes:
  my-db-volume:
    driver: local